### ISSUE TITLE
Hybrid issues

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/codeklavier-supercollider#2]
On my computer the clock of SC is very confused. It starts hello world at a value below 1 (not sure what- perhaps 0.5 or 0.2?) and then when I make it t.tempo= 2 is goes crazy. (see attached).
 When switching to Motippets the tempo is shifted. It should be t.tempo=1 but it's like the base value of the tempo correlation between the 2 prototypes is not correct so motippets ends up being twice as fast.
![error tempo](https://user-images.githubusercontent.com/27504577/37610490-fed936d2-2b9f-11e8-86aa-30afcd9ee0ac.jpeg)
3. Perhaps it might be better to also make the text for the gongs more minimal so that they stop pasting in themselves.

**Comment by narcode** [comment]
We can make the gongs in the env. Also with the last commit there are independent TempoClock objects for each prototype
